/**
 * The Orders screen quotes numbers to players. This checks they are still true.
 *
 * `packages/shared/src/forecast.ts` is generated by sweeping the real resolver,
 * which makes it correct on the day it is written and says nothing about the
 * day after. Any tuning change — encounter rates, damage, permit limits, the
 * pension formula — moves what the game does without touching the table, and
 * the failure mode is the worst kind: the screen keeps confidently quoting a
 * figure that stopped being true, and nothing anywhere says so.
 *
 * So this re-measures representative cells against the live resolver on every
 * run. When it fails, the fix is `npm run forecast -w @deepholdings/server`,
 * not a wider tolerance.
 *
 * The tolerance is deliberately loose. This is a drift alarm, not a precision
 * instrument: it is sampling a stochastic system with a fraction of the seeds
 * the committed table used, so it should catch "income halved" and stay quiet
 * about sampling noise. A tight bound here would fail randomly, and a test that
 * fails randomly gets muted, which is worse than not having one.
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import { FORECAST, RETREAT_STEPS, TICK_SECONDS, forecast } from '@deepholdings/shared';
import { measureCell } from '../tools/forecast.js';

/** Enough seeds to be meaningful, few enough to keep the suite quick. */
const RUNS = 10;
const TICKS = Math.round((2 * 24 * 3600) / TICK_SECONDS);

/** Cells that between them cover shallow/deep and reckless/cautious. */
const SAMPLES: readonly { depth: number; retreatPct: number }[] = [
  { depth: 4, retreatPct: 30 },
  { depth: 8, retreatPct: 35 },
  { depth: 12, retreatPct: 45 },
];

test('the published forecast still matches what the resolver does', () => {
  for (const { depth, retreatPct } of SAMPLES) {
    const column = RETREAT_STEPS.indexOf(retreatPct as (typeof RETREAT_STEPS)[number]);
    assert.notEqual(column, -1, `${retreatPct}% is not a measured column`);

    const published = FORECAST[depth - 1][column][0];
    const measured = measureCell(depth, retreatPct, RUNS, TICKS).goldPerHour;
    const drift = Math.abs(measured - published) / Math.max(1, published);

    assert.ok(
      drift < 0.4,
      `Floor ${depth} at ${retreatPct}%: the table says ${published} gold/hour, ` +
        `the resolver now produces ${measured} (${Math.round(drift * 100)}% out).\n` +
        `Regenerate it: npm run forecast -w @deepholdings/server -- --runs 24 --days 5`,
    );
  }
});

test('the forecast rises with depth, which is the promise the screen makes', () => {
  // "Deeper pays better" is written on the Orders screen as plain fact, and this
  // is the only thing that would notice if a tuning change made it false.
  //
  // Compared across a span rather than between neighbours, on purpose. These
  // are medians of a stochastic system, and adjacent deep floors legitimately
  // land within a gold or two of each other — Floor 11 measured 340 against
  // Floor 10's 341. Asserting strict neighbour-monotonicity would be asserting
  // that the sampling noise has a sign, and would fail on a rerun that changed
  // nothing.
  const cautious = RETREAT_STEPS.indexOf(45);
  const at = (depth: number) => FORECAST[depth - 1][cautious][0];

  for (let depth = 1; depth + 3 <= FORECAST.length; depth += 1) {
    assert.ok(
      at(depth + 3) > at(depth),
      `Floor ${depth + 3} (${at(depth + 3)}) does not pay better than Floor ` +
        `${depth} (${at(depth)}), so "deeper pays better" is no longer true.`,
    );
  }
});

test('a permit-capped target is quoted at the depth actually worked', () => {
  // The screen clamps to the permit before quoting. Without this a new player
  // at D-1 setting the slider to 12 would be promised Floor 12 money and get
  // Floor 2 money, which is the exact species of quiet lie this file exists to
  // prevent.
  const deep = forecast({
    targetDepth: 12, retreatPct: 45, lootPriority: 'gear', spendPolicy: 'resupply',
  });
  const shallow = forecast({
    targetDepth: 2, retreatPct: 45, lootPriority: 'gear', spendPolicy: 'resupply',
  });
  assert.ok(deep.goldPerHour > shallow.goldPerHour * 2);
});

test('loot priority and spend policy scale the forecast the way the resolver does', () => {
  const base = {
    targetDepth: 10, retreatPct: 40, lootPriority: 'gear', spendPolicy: 'resupply',
  } as const;

  // Relics are 2.1x value at 0.55 find chance, so 1.155 effective against
  // gear's 1.1 — a slight edge, not the doubling the raw multiplier suggests.
  const relics = forecast({ ...base, lootPriority: 'relics' });
  const gear = forecast({ ...base });
  assert.ok(relics.goldPerHour > gear.goldPerHour);
  assert.ok(relics.goldPerHour < gear.goldPerHour * 1.2);

  // Knowledge trades money for levels and must read as a real cost.
  assert.ok(forecast({ ...base, lootPriority: 'knowledge' }).goldPerHour < gear.goldPerHour);

  // Hoarding pays more per sale; insuring pays more pension and not more gold.
  assert.ok(forecast({ ...base, spendPolicy: 'hoard' }).goldPerHour > gear.goldPerHour);
  const insured = forecast({ ...base, spendPolicy: 'insure' });
  assert.equal(insured.goldPerHour, gear.goldPerHour);
  assert.ok(insured.pensionPerHour > gear.pensionPerHour);
});

test('pension and gold peak at different thresholds', () => {
  // The reason the screen shows two numbers instead of one. If this ever stops
  // being true the retreat slider has become a control with one right answer,
  // and the Orders screen should stop implying there is a decision to make.
  const deep = FORECAST[11];
  const goldPeak = deep.reduce((best, cell, i) => (cell[0] > deep[best][0] ? i : best), 0);
  const pensionPeak = deep.reduce((best, cell, i) => (cell[1] > deep[best][1] ? i : best), 0);

  assert.notEqual(
    RETREAT_STEPS[goldPeak],
    RETREAT_STEPS[pensionPeak],
    'Gold and pension now peak at the same retreat threshold, so the slider ' +
      'has a single dominant setting and is no longer a trade.',
  );
  assert.ok(RETREAT_STEPS[pensionPeak] < RETREAT_STEPS[goldPeak]);
});
