import { HOARD_SALE_BONUS, INSURE_PENSION_BONUS, LOOT_EFFECT } from './tuning.js';

/**
 * What each set of standing orders is worth, measured — not modelled.
 *
 * GENERATED by `npm run forecast -w @deepholdings/server`. Do not hand-edit:
 * `packages/server/test/forecast.test.ts` re-measures cells against the live
 * resolver and fails when this table has drifted, so an edit here becomes a
 * test failure rather than a lie on the Orders screen.
 *
 * Rows are target depth 1..12; columns are the retreat thresholds in
 * `RETREAT_STEPS`. Each cell is `[goldPerHour, pensionPerHour, hoursPerDeath]`
 * for a bare recruit with no department, no unlocks and no case files — which is
 * why the screen says "roughly" and why a geared player beats it.
 *
 * **Read the two currencies together.** Gold rises with caution all the way to
 * the top of the slider; pension peaks near 35% and falls off both sides,
 * because pension is paid at a death and a recruit who never dies never banks
 * any. That is the actual decision on this screen, and before this table it was
 * invisible to everyone including the people tuning it.
 *
 * Measured over 5 day(s) x 24 seeded careers per cell.
 */
export const RETREAT_STEPS = [10, 15, 20, 25, 30, 35, 40, 45] as const;

/** `[goldPerHour, pensionPerHour, hoursPerDeath]`, indexed `[depth - 1][step]`. */
export const FORECAST: readonly (readonly (readonly [number, number, number])[])[] = [
  // Floor 1
  [[46, 0, Infinity], [47, 0, Infinity], [47, 0, Infinity], [48, 0, Infinity], [46, 0, Infinity], [47, 0, Infinity], [47, 0, Infinity], [46, 0, Infinity]],
  // Floor 2
  [[90, 31, 55], [92, 0, Infinity], [91, 0, Infinity], [92, 0, Infinity], [91, 0, Infinity], [94, 0, Infinity], [91, 0, Infinity], [92, 0, Infinity]],
  // Floor 3
  [[96, 127, 3], [137, 52, 35], [140, 3, 320], [142, 0, Infinity], [139, 0, Infinity], [142, 0, Infinity], [142, 0, Infinity], [140, 0, Infinity]],
  // Floor 4
  [[97, 128, 3], [115, 150, 6], [177, 60, 45], [190, 10, 206], [193, 0, Infinity], [191, 0, Infinity], [188, 0, Infinity], [185, 0, Infinity]],
  // Floor 5
  [[97, 127, 3], [115, 149, 6], [154, 163, 11], [213, 75, 45], [227, 4, 576], [229, 2, 1440], [231, 0, Infinity], [229, 0, Infinity]],
  // Floor 6
  [[95, 128, 3], [116, 149, 6], [153, 174, 10], [203, 180, 18], [257, 58, 65], [273, 12, 360], [271, 0, Infinity], [274, 0, Infinity]],
  // Floor 7
  [[96, 127, 3], [113, 150, 6], [150, 173, 10], [193, 203, 14], [249, 157, 31], [284, 56, 115], [300, 14, 576], [302, 0, Infinity]],
  // Floor 8
  [[98, 128, 3], [117, 149, 6], [154, 176, 10], [196, 200, 15], [261, 191, 27], [275, 140, 45], [308, 52, 180], [321, 11, 720]],
  // Floor 9
  [[98, 128, 3], [115, 150, 6], [153, 174, 10], [195, 201, 14], [245, 224, 21], [289, 200, 36], [320, 130, 85], [340, 15, 960]],
  // Floor 10
  [[96, 128, 3], [116, 150, 6], [156, 177, 10], [194, 199, 14], [232, 226, 20], [302, 220, 44], [329, 187, 65], [341, 107, 192]],
  // Floor 11
  [[98, 127, 3], [115, 149, 6], [151, 174, 10], [201, 201, 15], [244, 228, 23], [293, 221, 37], [335, 174, 96], [340, 158, 125]],
  // Floor 12
  [[97, 128, 3], [115, 149, 6], [152, 174, 10], [193, 201, 14], [259, 229, 23], [286, 241, 33], [326, 169, 70], [351, 133, 160]],
];

/**
 * The forecast for a set of orders, interpolated between measured thresholds.
 *
 * Loot priority and spend policy are applied as the multipliers the resolver
 * itself uses rather than swept, because that is what they are: `LOOT_EFFECT`
 * scales realised value and `HOARD_SALE_BONUS` scales the sale. Relics are
 * worth their value times how often they are actually found.
 */
export function forecast(orders: {
  targetDepth: number;
  retreatPct: number;
  lootPriority: keyof typeof LOOT_EFFECT;
  spendPolicy: 'resupply' | 'hoard' | 'insure';
}): { goldPerHour: number; pensionPerHour: number; hoursPerDeath: number } {
  const row = FORECAST[Math.min(FORECAST.length, Math.max(1, orders.targetDepth)) - 1];

  // Between two measured thresholds, straight-line. The curve is smooth in this
  // range; pretending to more precision than eight sampled columns support
  // would be inventing numbers, which is the thing this file exists to avoid.
  const steps = RETREAT_STEPS;
  let lo = 0;
  while (lo < steps.length - 2 && steps[lo + 1] <= orders.retreatPct) lo += 1;
  const hi = Math.min(lo + 1, steps.length - 1);
  const span = steps[hi] - steps[lo];
  const t = span === 0 ? 0 : Math.min(1, Math.max(0, (orders.retreatPct - steps[lo]) / span));
  const blend = (a: number, b: number) =>
    !Number.isFinite(a) || !Number.isFinite(b) ? Infinity : a + (b - a) * t;

  const loot = LOOT_EFFECT[orders.lootPriority];
  const valueScale =
    (loot.value * loot.findChance) / (LOOT_EFFECT.gear.value * LOOT_EFFECT.gear.findChance);
  const saleScale = orders.spendPolicy === 'hoard' ? HOARD_SALE_BONUS : 1;

  return {
    goldPerHour: Math.round(blend(row[lo][0], row[hi][0]) * valueScale * saleScale),
    // Pension is service and depth, not loot, so the loot and sale multipliers
    // deliberately do not touch it. Insuring does raise it — that is the whole
    // of what the premium buys.
    pensionPerHour: Math.round(
      blend(row[lo][1], row[hi][1]) * (orders.spendPolicy === 'insure' ? INSURE_PENSION_BONUS : 1),
    ),
    hoursPerDeath: blend(row[lo][2], row[hi][2]),
  };
}
