-- A retried purchase must not charge twice.
--
-- Keyed on (account_id, key) rather than key alone, for the same reason
-- `push_sends` is: the key is generated by a client, and one player's key must
-- never be able to collide with another's. The insert *is* the deduplication —
-- that is a property of the primary key, not of the caller being careful.
--
-- `status` is NULL while a request is in flight. That is the reservation: the
-- first request to insert the row owns the work, and a concurrent duplicate
-- sees NULL and is refused rather than racing it.
--
-- `request_hash` catches a client reusing a key for a different request. Without
-- it, a buggy or malicious caller could send one key with two bodies and be
-- handed the first body's response for the second body's request, which is a
-- worse failure than the double-charge this table exists to prevent.
CREATE TABLE IF NOT EXISTS idempotency_keys (
  account_id   UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  key          TEXT NOT NULL,
  route        TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  status       INTEGER,
  response     JSONB,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (account_id, key)
);

-- Expiry sweeps by age, so the scan has to be by age.
CREATE INDEX IF NOT EXISTS idempotency_keys_created_idx ON idempotency_keys (created_at);
