/**
 * Generates every Android launcher icon and splash from one definition.
 *
 * Rendered rather than drawn by hand or generated by a model, for one reason:
 * an icon is judged at 48dp and lives or dies on crisp geometry at exact
 * palette values. `#ffb742` here is the same `--phosphor-bright` the game uses,
 * and the shapes are flat fills with hard edges rather than a resampled raster.
 *
 * The composition came out of a Krea 2 generation — asked for a flat icon of
 * this design, it returned a rounded-square bezel that read better than the
 * squared-off frame I had drawn. Its palette was a navy-black rather than the
 * game's, and its edges were soft, so the idea was kept and redrawn here.
 *
 *   node tools/make-icons.mjs
 *
 * Then `npx cap sync android`. CI's `git diff --exit-code` on android/ will
 * fail if the committed icons drift from what this produces.
 */
import { chromium } from 'playwright-core';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const RES = join(HERE, '..', 'android', 'app', 'src', 'main', 'res');
const STORE = join(HERE, '..', '..', '..', 'docs', 'store');

/** The game's own palette. Kept in sync with client/src/styles/tokens.css. */
const BEZEL = '#d8cdb4';
const SCREEN = '#14100c';
const AMBER = '#ffb742';

/**
 * The mark, at a nominal 512.
 *
 * `inset` is how much bezel shows around the screen. On the adaptive
 * foreground there is none — the bezel is the background layer, and the
 * foreground carries only the screen, sized to sit inside the 66/108 safe
 * circle that every launcher mask is guaranteed to keep.
 */
function mark({ size = 512, bezel = true, screenScale = 0.75 }) {
  const screen = Math.round(size * screenScale);
  const radius = Math.round(screen * 0.17);
  const caret = Math.round(screen * 0.5);
  const cursorW = Math.round(screen * 0.19);
  const cursorH = Math.round(screen * 0.34);
  const gap = Math.round(screen * 0.045);
  return `
<div style="
  width:${size}px;height:${size}px;
  background:${bezel ? BEZEL : 'transparent'};
  display:flex;align-items:center;justify-content:center;
">
  <div style="
    width:${screen}px;height:${screen}px;
    background:${SCREEN};border-radius:${radius}px;
    display:flex;align-items:center;justify-content:center;gap:${gap}px;
  ">
    <span style="
      font-family:'Plex',monospace;font-weight:600;font-size:${caret}px;
      line-height:1;color:${AMBER};margin-top:-${Math.round(caret * 0.06)}px;
    ">&gt;</span>
    <span style="width:${cursorW}px;height:${cursorH}px;background:${AMBER};"></span>
  </div>
</div>`;
}

const FONT = `
@font-face {
  font-family: 'Plex';
  src: url('file://${join(HERE, '..', '..', '..', 'node_modules', '@fontsource', 'ibm-plex-mono', 'files', 'ibm-plex-mono-latin-600-normal.woff2')}') format('woff2');
  font-weight: 600;
}
* { margin:0; padding:0; box-sizing:border-box; }
body { background: transparent; }`;

/**
 * playwright-core rather than playwright: it is a couple of megabytes and
 * downloads no browsers. This renders with a Chromium you already have, which
 * on any machine that can build an APK is a safe assumption. Point `CHROMIUM`
 * at it if the guesses below miss.
 */
const CANDIDATES = [
  process.env.CHROMIUM,
  process.env.PLAYWRIGHT_BROWSERS_PATH && `${process.env.PLAYWRIGHT_BROWSERS_PATH}/chromium/chrome-linux/chrome`,
  '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
  '/usr/bin/chromium',
  '/usr/bin/chromium-browser',
  '/usr/bin/google-chrome',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
].filter(Boolean);

const executablePath = CANDIDATES.find((path) => existsSync(path));
if (!executablePath) {
  console.error(
    'No Chromium found. Set CHROMIUM to a Chrome/Chromium binary:\n  ' +
      CANDIDATES.join('\n  '),
  );
  process.exit(2);
}

const browser = await chromium.launch({ executablePath });
const page = await browser.newPage({
  viewport: { width: 1400, height: 1400 },
  deviceScaleFactor: 1,
});

async function render(html, path, size) {
  writeFileSync('/tmp/_icon.html', `<style>${FONT}</style>${html}`);
  await page.goto('file:///tmp/_icon.html');
  await page.waitForTimeout(220);
  mkdirSync(dirname(path), { recursive: true });
  await page.locator('body > div').screenshot({ path, omitBackground: true });
  return `${path.replace(RES, 'res').replace(STORE, 'docs/store')}  ${size}px`;
}

const written = [];

/**
 * Legacy launcher icons. Square; the launcher rounds them however it likes,
 * which is why the glyph sits well inside the bezel.
 */
const LEGACY = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
for (const [density, size] of Object.entries(LEGACY)) {
  for (const name of ['ic_launcher', 'ic_launcher_round']) {
    written.push(
      await render(mark({ size, screenScale: 0.75 }), join(RES, `mipmap-${density}`, `${name}.png`), size),
    );
  }
}

/**
 * Adaptive foreground, 108dp canvas.
 *
 * Only the middle 66 of 108 is guaranteed to survive the mask — the rest is
 * bleed the launcher may crop to a circle, squircle, teardrop or whatever else
 * it fancies. 0.55 keeps the whole screen comfortably inside that, and the
 * beige background layer fills everything the mask keeps.
 */
const ADAPTIVE = { mdpi: 108, hdpi: 162, xhdpi: 216, xxhdpi: 324, xxxhdpi: 432 };
for (const [density, size] of Object.entries(ADAPTIVE)) {
  written.push(
    await render(
      mark({ size, bezel: false, screenScale: 0.55 }),
      join(RES, `mipmap-${density}`, 'ic_launcher_foreground.png'),
      size,
    ),
  );
}

/** Play Store listing icon. Not shipped in the APK. */
written.push(await render(mark({ size: 512, screenScale: 0.75 }), join(STORE, 'icon-512.png'), 512));

/**
 * Splash.
 *
 * Flat screen-black with the mark centred, rather than the generated key art.
 * The app boots into a stylised CRT sequence, and a photographic splash ahead
 * of it is a tonal cut from one medium to another in the first second of the
 * game. It would also add five densities of photograph to the APK for
 * something on screen for under a second. The key art earns its keep on the
 * store listing, where someone is deciding whether to install at all.
 */
const SPLASH = {
  'port-mdpi': [320, 480], 'port-hdpi': [480, 800], 'port-xhdpi': [720, 1280],
  'port-xxhdpi': [960, 1600], 'port-xxxhdpi': [1280, 1920],
  'land-mdpi': [480, 320], 'land-hdpi': [800, 480], 'land-xhdpi': [1280, 720],
  'land-xxhdpi': [1600, 960], 'land-xxxhdpi': [1920, 1280],
};
for (const [density, [w, h]] of Object.entries(SPLASH)) {
  const glyph = Math.round(Math.min(w, h) * 0.34);
  const html = `<div style="width:${w}px;height:${h}px;background:${SCREEN};display:flex;align-items:center;justify-content:center;">${mark(
    { size: glyph, screenScale: 1 },
  )}</div>`;
  written.push(await render(html, join(RES, `drawable-${density}`, 'splash.png'), `${w}x${h}`));
}
// The density-less fallback Capacitor also references.
{
  const html = `<div style="width:480px;height:800px;background:${SCREEN};display:flex;align-items:center;justify-content:center;">${mark(
    { size: 163, screenScale: 1 },
  )}</div>`;
  written.push(await render(html, join(RES, 'drawable', 'splash.png'), '480x800'));
}

await browser.close();
console.log(written.join('\n'));
console.log(`\n${written.length} files written. Run: npx cap sync android`);
